name: flask 
on:
  push: 
      branches: [ master ]

  job: 
      docker: #job's name is docker, rub job by ubuntu-lastet
        runs-on: ubuntu-lastet
        steps: #define the steps
          - name: checkout #pull source this code in git repository about the ubuntu virtual machine running this job
            user: action/checkout@v2
