name: flask-hellowolld 
on:
  push: 
      branches: [ master ]
   
   
jobs: 
    docker: 
      runs-on: ubuntu-lastet
      steps: 
        - name: checkout 
          uses: action/checkout@v2
        - name: Login Dock hub
          uses: docker/login-action@v1
          with:
           username: ${{ secret.DOCKERHUB_USERNAME }}
           password: ${{ secret.DOCKERHUB_ACCESS_TOKEN }}
        - name: setup Docker Buildx
          uses: docker/setup-buildx-action@v1
          id: buildx
          
